### ISSUE TITLE
Feature request: Automatically change depending on sunset?

### ISSUE THREAD

**Issue by martinfjant** [muuvmuuv/vscode-sundial#1]
This is an amazing plugin (especially since VSCode don't support Mojave's native dark mode..). I live up in the cold north, and the time of daylight changes quite fast, so manually editing when it is supposed to change form light to dark would almost require me to do it everyday if I wanted it to be in sync with the sunlight outside.

Would it be possible, perhaps, to have the function to change to dark when the sun sets rather than at a predefined time? There is a nice little programme that does this for the OS, https://nightowl.kramser.xyz, and f.lux and the native night shift have been doing it since long.

**Comment by muuvmuuv** [comment]
Nice idea! Thought about the same. I'll work on this when I get my MacBook back from the support.

**Comment by muuvmuuv** [comment]
@martinfjant You should be fine with the new release. Please try it and tell me if this is what you have been looking for. 😄

**Comment by martinfjant** [comment]
Wow, this is amazing! Thank you! :heart:

**Comment by muuvmuuv** [comment]
Your welcome!

**Comment by martinfjant** [comment]
No, now that I've tried it I'm afraid to report that nothing happens! Not sure if it's my set up, or the plugin itself, that is making it not working.

**Comment by muuvmuuv** [comment]
Can you post your configuration @martinfjant please

**Comment by martinfjant** [comment]
I had the standard settings, so my configuration was.. blank as for sundial.anything. I'll try add the standard settings to my config and see if anything changes. Here are my config file:
 `{
    "terminal.integrated.fontFamily": "'InconsolataForPowerline Nerd Font'",
    "terminal.integrated.fontSize": 18,
    "workbench.iconTheme": "vscode-icons",
    "vsicons.projectDetection.autoReload": true,
    "[elm]": {
        "editor.formatOnSave": true
    },
    "javascript.validate.enable": false,
    "editor.fontLigatures": true,
    "editor.fontFamily": "Fira Code",
    "workbench.fontAliasing": "antialiased",
    "editor.fontSize": 14,
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "javascript.implicitProjectConfig.checkJs": true,
    "javascript.referencesCodeLens.enabled": true,
    "eslint.enable": false,
    "prettier.jsxBracketSameLine": true,
    "html.format.wrapAttributes": "force-aligned",
    "javascript.autoClosingTags": false,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
    "window.nativeTabs": true,
    "window.titleBarStyle": "native",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "css.lint.duplicateProperties": "warning",
    "css.lint.float": "warning",
    "css.lint.idSelector": "warning",
    "html-css-class-completion.enableEmmetSupport": true,
    "elm.analyseEnabled": true,
    "html.autoClosingTags": false,
    "prettier.trailingComma": "es5",
    "editor.tabCompletion": "on",
    "editor.cursorStyle": "line-thin",
    "breadcrumbs.enabled": true,
    "workbench.editor.swipeToNavigate": true,
    "terminal.external.osxExec": "iterm",
    "terminal.integrated.shell.osx": "/usr/local/bin/fish",
    "workbench.colorTheme": "Light+ Tweaked",
    "sundial.autoLocale": true,
    "sundial.dayTheme": "Default Light+",
    "sundial.interval": 5,
    "sundial.nightTheme": "Default Dark+",
}`

I just now added the sundial.stuff, so it was like it is above without that before. But it should be working fine with no settings at all, I presume?

**Comment by muuvmuuv** [comment]
@martinfjant figured it out. Will fix this soon. Try to set your location manually instead

**Comment by martinfjant** [comment]
It works now! <3
