### ISSUE TITLE
Modify settings.json depending on night/day

### ISSUE THREAD

**Issue by Gonzalo933** [muuvmuuv/vscode-sundial#3]
I'm using the extension Bracket Pair Colorizer to color pairs of brackets in the editor. The problem is that colors that work well at night don't work well during daytime. These colors can be changed by modifying the file settings.json.

I think a good feature would be to add a new option for sundial in which you can specify lines to add/remove to the settings.json file depending of the time of the day.

**Comment by muuvmuuv** [comment]
I had the same problem with EOL Plugin. Interesting Idea! Choosing lines wouldn't make much sense as the settings file is dynamic. Better would be choosing the key and set day/night values. I will investigate this is the near future. Their are some bugs I need to fix before I go to that but I think a separate "settings.json" file would make sense, e.g.: day.json/night.json

**Comment by Gonzalo933** [comment]
I think it's an easy feature to implement. There are some extensions that have done something similar:

https://github.com/freetonik/vscode-dnts/blob/master/src/extension.ts

So maybe if I get some time I could try to do a PR

**Comment by muuvmuuv** [comment]
@Gonzalo933 sounds great! I have some other things to do first, so it would be nice to welcome you as my first contributor :)=

**Comment by Gonzalo933** [comment]
I will try to get to it next month, I will have some free time then

**Comment by muuvmuuv** [comment]
@Gonzalo933 give the latest version a try and tell me if that worked for you

**Comment by Gonzalo933** [comment]
I'm having a bit of a problem making it work.

If I use the command: Sundial: Night Theme it does change my settings as expected but the selected theme is: `"workbench.colorTheme": "Dark+"` and VSCode says that theme does not exist, in my VSCode version 1.32.3 the theme is called: "Default Dark+".

Also changing the setting `"sundial.nightTheme": "Default Dark+"` does not seem to work as it keeps using just "Dark+" as night theme

**Comment by Gonzalo933** [comment]
well, it did change my theme automatically at night.

**Comment by muuvmuuv** [comment]
I'll have a look at this

**Comment by muuvmuuv** [comment]
Ah, found the issue. I forgot to update the config settings before checking which theme is active which prevented the script from toggling. Update to the latest version and check if its working now.

**Comment by Gonzalo933** [comment]
It is working as expected now, and the settings get applied depending night/day. Thank you!
