### ISSUE TITLE
[FEATURE] Use future Code API to detect preferred scheme

### ISSUE THREAD

**Issue by VideoPlayerCode** [muuvmuuv/vscode-sundial#40]
Hey everyone. Your extension looks nice, but it's a shame that it's mac-only.

Read the bottom of this comment:
https://github.com/microsoft/vscode/issues/61519#issuecomment-558738593

There is a JavaScript query, supported by V8/Electron (VSCode's GUI engine), which tells you whether dark mode is enabled or disabled on the system.

So you can rip out all the ugly macOS-specific code and replace it with this. :-)

**Comment by muuvmuuv** [comment]
Thank you for opening the issue! I will try to use the CSS media query solution today, but would love to see that the VS Code team will implement the electron native solution ASAP.

**Comment by muuvmuuv** [comment]
@VideoPlayerCode How have you accessed the `window`? VS Code always tells me `window is not defined`.

**Comment by VideoPlayerCode** [comment]
You're welcome. Your extension looks great by the way.

Hmm. With Help - Show Developer Tools. I did it in the console there. Hmm. I really hope there is some way for extensions to access window. Although window is just used for guaranteed namespacing. In JS browsers, that prefix is optional. So try calling `matchMedia` without `window.` prefix.

**Comment by VideoPlayerCode** [comment]
Hi again @muuvmuuv, the vscode ticket has died after your post ten days ago. What are your current plans? Could you share your plans with the official ticket, or if you don't have time, let them know so someone else can work on it. :-)

**Comment by muuvmuuv** [comment]
As I'm planning to expose an API to VS Code that sends the preferred scheme or a getter which returns it. I'll change the purpose of this issue a little:

**Comment by VideoPlayerCode** [comment]
That's great news. I replied in the vscode discussion. :-)
