### ISSUE TITLE
[BUG] – Continuous errors when offline

### ISSUE THREAD

**Issue by DOFfactory** [muuvmuuv/vscode-sundial#41]
**Describe the bug**

I have continuous pop-up errors when I am working in VSCode, as your extension unsuccessfully tries to reach some server for the automatic geo-location.

**To Reproduce**

Go offline, wake up the computer from sleep, do not connect to wifi, and have enabled automatic geolocation for this extension.

**Expected behavior**

It should remember the data from the last sync with the geolocation server, if the data is for example older than 10 days (think about holidays), it should have a fallback option to the manual time settings.

**Screenshots**

**Desktop (please complete the following information):**

- MS Windows 10 1903 Build 18362
- VS Code 1.40.2

**Comment by muuvmuuv** [comment]
Thanks for the issue! Which version of Sundial do you have installed? As I know, I already fixed that issue but for a later VS Code version, so updating VS Code and Sundial should do it.

**Comment by DOFfactory** [comment]
Thanks for getting back to me. It is 1.16.0.

**Comment by muuvmuuv** [comment]
Go and try this version. I have fixed several bugs with auto locale und it should now cache your location and do not call it that often. The message should now only appear if it not had the chance to cache your location.
