### ISSUE TITLE
Option to disable Touch Bar Menus

### ISSUE THREAD

**Issue by lolleko** [muuvmuuv/vscode-sundial#42]
The Touch Bar entries conflict with other extensions and custom Touch Bar functionality.

**Comment by muuvmuuv** [comment]
True, encountered a similar issue a while ago. 
Can you tell me with which it conflicts, which VS Code version and Sundial version you have?

And next time, please use the issue templates, they are there to help prevent asking the same question in every issue again and again :)

**Comment by lolleko** [comment]
It never conflicted it just showed sun dials day/night theme buttons on the Touch Bar instead of my custom ones.
I think it prioritises the buttons that have been added most recent when the Touch Bar runs out fo space.

"Conflicting" extension: https://marketplace.visualstudio.com/items?itemName=felipe.nasc-touchbar

---

I just realised that there is built in functionality for ignoring/disabling Touch Bar elements in vanilla VSCode:

You can specify a list of commands/menus you don't want to show up in the touchbar with the following setting:

```
"keyboard.touchbar.ignored": [
  "sundial.switchToNightTheme",
  "sundial.switchToDayTheme"
]
```
You might want to mention that in the readme somewhere.

You could also change the label of the buttons to just use emojis 🌞/🌑  (so they take up less space).

Very useful extension btw, thanks a lot!

**Comment by muuvmuuv** [comment]
As long as there is an option to disable this, I'll keep this "on hold" as long as I'm working on implementing "auto theme switch" natively to VS Code core. This would require me to rebuild Sundial core. I'll update the buttons directly after that, the suggestion is good, with simplifying the touch bar text.

**Comment by muuvmuuv** [comment]
I'm going to remove this feature completely because I don't think it is good at all ^^ the plugins indicates to automatically changing the theme. People who want to do it manually can use the command. Major release will come soon.
