### ISSUE TITLE
[FEATURE] Remove auto theme switch based on OS appearance

### ISSUE THREAD

**Issue by muuvmuuv** [muuvmuuv/vscode-sundial#43]
**Is your feature request related to a problem? Please describe.**

Because I'm going to implement this feature natively to VS Code, this isn't longer needed in Sundial.

**Describe the solution you'd like**

Remove it from Sundial core and add a hint that any other feature in Sundial would need the options in Code `colorThemeAutoSwitch` to be off (or whatever the option will be named in release)

**Describe alternatives you've considered**

None

**Additional context**

- Depends on: https://github.com/microsoft/vscode/issues/61519

**Comment by mikestopcontinues** [comment]
Thanks for all the work you're doing on this. It's totally ace!
