### ISSUE TITLE
[FEATURE] Allow to manually switch theme until next cycle

### ISSUE THREAD

**Issue by davidfilat** [muuvmuuv/vscode-sundial#44]
**Is your feature request related to a problem? Please describe.**

Whenever I manually switch to some other theme, immediately the extensions switches back to the Sundial Day/Night Theme. But for some files I really like to switch the Color Theme, because the syntax highlighting is more appropriate.

**Describe the solution you'd like**

I would like to be able to switch manually the Color Theme without Sundial automatically switching the theme until the next theme switching event (when the extensions switches to the Day/Night theme). For example if I switch manually the theme at 3pm, I want it to stay so until 6 pm when the Sundial dark theme kicks in. 

**Describe alternatives you've considered**

I tried removing all event in the `sundial.windowEvent` and `sundial.workspaceEvents`, but it didn't work.

`"sundial.windowEvents": [],`
`"sundial.workspaceEvents": []`

**Comment by muuvmuuv** [comment]
Hey, I wont have time until 6. of Jan but it seems related to something I‘m already working on. Since I have developed the theme switch into VS Core a couple of days ago I will anyway wait for the next release, because I would need to completely reimplement some things

**Comment by davidfilat** [comment]
> Hey, I wont have time until 6. of Jan but it seems related to something I‘m already working on. Since I have developed the theme switch into VS Core a couple of days ago I will anyway wait for the next release, because I would need to completely reimplement some things 

Great! I am looking forward for the next release!

**Comment by muuvmuuv** [comment]
Is it fixed now?

**Comment by davidfilat** [comment]
> Is it fixed now?

Not for me. I've updated the extension to version 2.2.0, but it immediately switches to the  workbench.preferredDarkColorTheme (or Light) if I change the theme to one that is not set as preferred.

**Comment by muuvmuuv** [comment]
Okay, so, this is impossible. I would need to listen for changes on `workbench.colorTheme` and then deactivate the extension until next circle BUT since Sundial also changes that setting when changing your theme it would simply deactivate itself every time. I'm sorry for this but it would require too much hacking around. 

What I could do is provide a command that deactivates Sundial checks and maybe(!) as well reactivates on next circle. Would that be enough?

**Comment by muuvmuuv** [comment]
Check if it works with the new command @davidfilat
