### ISSUE TITLE
[FEATURE] Move extension logs to Output card

### ISSUE THREAD

**Issue by nawordar** [muuvmuuv/vscode-sundial#45]
**Is your feature request related to a problem? Please describe.**

The extension currently floods the Debug Console with non-error messages. This is quite frustrating when I try to debug problems with my own extensions or VSCode.
![Screenshot_20200130_194954](https://user-images.githubusercontent.com/26769700/73480493-46331980-439a-11ea-8dd0-61c25a916e83.png)
![image](https://user-images.githubusercontent.com/26769700/73480548-5c40da00-439a-11ea-8bf0-f96e472b36ab.png)

**Describe the solution you'd like**

Other extensions print this kind of information on the Output card e.g.:

![image](https://user-images.githubusercontent.com/26769700/73480641-8db9a580-439a-11ea-8d36-d18d782188ce.png)

**Comment by muuvmuuv** [comment]
Good idea! Will add this as soon as VS Code releases my changes.
