### ISSUE TITLE
How to ignore terminal?

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [muuvmuuv/vscode-sundial#46]
Hey, great extension made me finally switch to vsc from atom ;)

How can I set it up, that I have a fixed (no day/night change) theme of my choice for the terminal in vsc?

**Comment by muuvmuuv** [comment]
This isn't possible, I'm sorry. I'm just changing the theme as this is something the theme is responsible for. There is no choice of "terminalColorScheme" yet, but if you want this feel free to open an issue on the VS Code main repository and add me, so I can subscribe and add it in the future if they're going to implement it.
