### ISSUE TITLE
Does the latest version of the plugin no longer support the feature of automatically changing the VSCode theme based on the operating system theme?

### ISSUE THREAD

**Issue by p5ydn0** [muuvmuuv/vscode-sundial#48]
I found that there is no related setting of `sundial.systemTheme` before. Thank you.

**Comment by muuvmuuv** [comment]
Please read the README => https://github.com/muuvmuuv/vscode-sundial#installation

Switching based on OS Appearance is build in now! I have submitted a PR to VS Code and they released it in the latest version compatible with the latest Sundial (breaking change)

**Comment by p5ydn0** [comment]
@muuvmuuv 

Hi, thank you for your reply. I have read the README file many times, and because of my limited ability, I still have n’t successfully set the "Transform VSCode theme with system theme (Dark / Light)".The setting json file is as follows:

```json
"window.autoDetectColorScheme": true, // required!
"workbench.preferredLightColorTheme": "Eva Light",
"workbench.preferredDarkColorTheme": "Eva Dark",
```

After I follow the above settings, the effect is that VSCode can be transformed according to the theme, but as soon as I click on the VSCode theme, it will return to the original theme.

I also tried other settings, but still failed.

Excuse me, can you give an example of a correct setup? thank you very much!

***
* macOS Version: 10.15.3
* VSCode Version: 1.42.1

**Comment by muuvmuuv** [comment]
What do you mean with "but as soon as I click on the VSCode theme"?

If you want to use that build in feature, you can just disable Sundial.

**Comment by p5ydn0** [comment]
@muuvmuuv

This means that whenever I click on the interface of VSCode. 

You do not know what I mean.

**Comment by muuvmuuv** [comment]
So, as I understood, you want your theme changed based on the system appearance, right? The settings you have posted for that are correct BUT if you have Sundial installed, you should disable it, have you done that? I do not check if `autoDetectColorScheme` is set to `true` (but I should ^^), and that may cause incidents if the default Sundial settings get in the way with the current OS appearance.
