### ISSUE TITLE
Error: Setting has invalid type, expected "string". Fix in JSON.

### ISSUE THREAD

**Issue by vishrutarya** [muuvmuuv/vscode-sundial#49]
**Themes are not auto-updating.**

The themes are not auto-updating and there is the following error message on the settings pane:

`Setting has invalid type, expected "string". Fix in JSON.`.

Some other functionality appears to work, namely that I can use `ctrl+cmd+t` to switch btw light and dark themes.

**To Reproduce**

1. Install theme
2. Go to Settings (`cmd+,`)
3. See errors

**Expected behavior**

1. The themes auto-switch.
2. The error messages don't appear.

**Screenshots**

Here's the screenshot of the Settings pane, including the error messages:
![image](https://user-images.githubusercontent.com/12104721/82066815-c1d48000-9684-11ea-91a4-b88b2960e6df.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- VS Code: 
```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
- Sundial: 2.3.0

**Comment by muuvmuuv** [comment]
Hey, thanks for opening the issue. I will take a look the next days. Maybe it was an API change in some release.

**Comment by vishrutarya** [comment]
The problem has self-resolved! Closing.

**Comment by muuvmuuv** [comment]
How? 😄

**Comment by vishrutarya** [comment]
🤷‍♂️

If I find out I’ll update here :-)
