### ISSUE TITLE
[FEATURE] Please also publish your extension on open-vsx.org

### ISSUE THREAD

**Issue by DanScharon** [muuvmuuv/vscode-sundial#50]
Hi,

VSCodium currently only supports installing extensions from [open-vsx.org](https://open-vsx.org). Therefore it would be awesome if you could publish your extension there as well :)

The process of how to publish there is described [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). 

Thank you!

**Comment by muuvmuuv** [comment]
Done: https://open-vsx.org/extension/muuvmuuv/vscode-sundial

**Comment by DanScharon** [comment]
wow, that was quick 😃 thank you!
