### ISSUE TITLE
[BUG] Extension does not run after sunset

### ISSUE THREAD

**Issue by tedhudek** [muuvmuuv/vscode-sundial#52]
**Describe the bug**

No theme change after sunset. (haven't tested sunrise)

I verified that `window.autoDetectColorScheme` is not checked (default).  I enabled the extension before sunset, but it is now 50 minutes past sunset and no theme change.  Are there logs somewhere I can look at?

**Desktop (please complete the following information):**

```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

Here are my settings for Sundial v2.3.0:

```
    "workbench.preferredDarkColorTheme": "Cobalt2",
    "sundial.nightVariable": 20,
    "sundial.latitude": "47.6",
    "sundial.longitude": "-122.3"
```

**Comment by tedhudek** [comment]
It didn't run for sunrise either.

**Comment by tedhudek** [comment]
Update - it have been as simple as reloading VS Code, which I had not done.  I just closed and restarted Code, and the theme changed.  I will make a PR to the readme to recommend the restart.

**Comment by muuvmuuv** [comment]
Hey, thanks for opening that issue. Normally it shouldn't require any restart (tested on mine with your coordinates, and it changed immediately). Did you have set both theme preferences?

```json
  "workbench.preferredLightColorTheme": "GitHub Light",
  "workbench.preferredDarkColorTheme": "GitHub Dark",
```

You have also set `nightVariable` which means 20 minutes after your real sunset. Weird it doesn't change after 50min. 

There are logs <kbd>CMD+Shift+P</kbd> → "View: Output" → Select "Sundial" in the upper right select menu.
