### ISSUE TITLE
[FEATURE] Doesn't appear in the search "auto night mode" on extensions store

### ISSUE THREAD

**Issue by aderchox** [muuvmuuv/vscode-sundial#54]
OK, not quite a "feature request", but I found your extension completely by luck, because if one searches "auto night mode" in the extensions, this doesn't appear in the vscode's results, or at least not in the top ~20 ones or so(I don't usually go deep down).

I don't know how, but maybe you could add some keywords or something like that so that it gets brought up when people search for it? I just want the people to find this and help their eyes. :)
(Thank you very much for this extension).

**Comment by aderchox** [comment]
Please be aware that I just also tried "toggle night" and this doesn't bring it up in the search as well. :)

**Comment by muuvmuuv** [comment]
Good catch, I use my extension because it just works for me, so never cared about that xD. I will have a look at it. I have already added keywords since begining, I wonder why VS Code doesn't use them. Maybe an API change I haven't noticed.

**Comment by muuvmuuv** [comment]
Okay, it seems they are limited, so I need to be more explicit.

> An array of keywords to make it easier to find the extension. These are included with other extension Tags on the Marketplace. This list is currently limited to 5 keywords.

**Comment by muuvmuuv** [comment]
I will try something tonight (GMT+1). I have no idea if phrases like "auto night mode" are allowed as a keyword, but I will try to combine some keywords into one and see if searching gets better.

**Comment by muuvmuuv** [comment]
I am unable to publish.. will investigate this *** later in the week. Just generated 100 tokens unsuccessfully. Even *vsce* does not work. Maybe my router or something.

**Comment by muuvmuuv** [comment]
Do you mind checking again? I was able to publish a fix now.

**Comment by aderchox** [comment]
Yes, now the "auto night mode" works. Your extension is 9th on my list. But it's still obvious enough as it's not down the scroll area. On "toggle night", I can't seem to find it, but not's a problem because IMO it's good enough that it appeared in my first search. Thank you.

**Comment by muuvmuuv** [comment]
Yeah, it seems Microsoft just isn't concerned about keyword search it just must match, and I think I just found a perfect middle.
