### ISSUE TITLE
[BUG] Dark theme is applied instead of the light one

### ISSUE THREAD

**Issue by aderchox** [muuvmuuv/vscode-sundial#55]
**Describe the bug**
See this please:
![image](https://user-images.githubusercontent.com/52244768/134815561-0d351a3d-1755-41f6-91c3-f2220774fa7f.png)
According to my timezone, it must turn on the light theme, but the dark theme is applied.

**To Reproduce**
Well, yesterday it worked correctly, but today it got my day/night wrong (_at least apparently_).

**Expected behavior**
Light theme must be on. Am I doing anything wrong?

**Desktop (please complete the following information):**

- OS: [e.g. macOS 10.14.4] Windows 10
- VS Code: [e.g. 1.33.1] 1.60.2
- Sundial: [e.g. 1.16.0] 2.6.0

**Comment by muuvmuuv** [comment]
Can you turn on logging and copy-paste the log output here?

I guess it is because of this part: https://github.com/muuvmuuv/vscode-sundial/blob/main/src/sundial.ts#L128-L145

You have to comment out lat and long to get exact times to be applied. Reading my code, I realize that it would make more sense to switch that order to reduce network calls.

**Comment by aderchox** [comment]
> Can you turn on logging and copy-paste the log output here?
> 
> I guess it is because of this part: https://github.com/muuvmuuv/vscode-sundial/blob/main/src/sundial.ts#L128-L145
> 
> You have to comment out lat and long to get exact times to be applied. Reading my code, I realize that it would make more sense to switch that order to reduce network calls.

Sorry not a JS pro and I'm not quite sure how I can turn on the logging for a certain extension on vscode? Do you mean opening the `Developer: Show Logs...`? I opened it and searched "sundial" and these two lines is all I have:
> [2021-09-26 23:37:00.086] [exthost] [info] ExtensionService#_doActivateExtension muuvmuuv.vscode-sundial {"startup":true,"extensionId":{"value":"muuvmuuv.vscode-sundial","_lower":"muuvmuuv.vscode-sundial"},"activationEvent":"*"}
> [2021-09-26 23:37:00.086] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/aderchox/.vscode/extensions/muuvmuuv.vscode-sundial-2.6.0/dist/extension.js
Do you mean something else?

**Comment by muuvmuuv** [comment]
You can enable debugging with `sundial.debug: true` and in the VS Code logs panel there must be a dropdown where somewhere should "Sundial" appear.

If a lat and log is set, a script will determine your sunset and sunrise based on that location and overrides the manually set value. So using both does not work. 

What do you mean by comparing to the user system local time? Without the extension would not work ^^. As you can see here I compare against local system time: https://github.com/muuvmuuv/vscode-sundial/blob/main/src/sundial.ts#L156-L161
