### ISSUE TITLE
[BUG] When connected to a VPN the extension cannot fetch location

### ISSUE THREAD

**Issue by MarcolinoPT** [muuvmuuv/vscode-sundial#56]
**Describe the bug**

When the option `Auto locale` is active and a VPN connection is also active the extension throws an exception.
This forces the extension to set the wrong theme and we have disabled the option `Auto locale` and entered manual coordinates or time for proper behavior.
At first it seemed like this could be solved by not using a VPN to establish a connection and use the one on cache, given the error description. After trying that approach the error persists.

**To Reproduce**

1. Open VS Code
2. Go to extension settings
3. Enable 'Auto locale'
4. Connect to a VPN location
5. There should be a notification/pop up displaying an error

**Expected behavior**

No error notification and configured theme displayed according to geo-location.

**Screenshots**

![image](https://user-images.githubusercontent.com/18648315/149890884-5fdc51b7-9199-4696-8dbc-fd9e05c3a924.png)

**Desktop (please complete the following information):**

- OS: Windows 11 21H2 build 22000.434
- VS Code: 1.63.2
- Sundial: 2.6.2

**Comment by muuvmuuv** [comment]
Interesting. I never used a VPN with it, but it is definitely not a solution to disable it temporary ^^. Which VPN are you using and did you trying another one? I could imagine that the VPN is blocking my "online test"... still waiting for VS Code giving me an API for that...

**Comment by MarcolinoPT** [comment]
I use PurePVN and Cisco AnyConnect. The issue happens with either of them. ☹️ 
Yes, most probably the VPN is blocking it, hadn't had the chance to dive deep into this to confirm it 😊

**Comment by muuvmuuv** [comment]
Interesting. I am using cloudflare to detect the online status. I don't think your VPN blocks the internet tho xD

Can you test this for me on both of your connections? I am at work now and moving into a new apartment this and next month so idk when I have time for it after work.

```js
import { lookup } from "node:dns"

lookup(
  "www.cloudflare.com",
  {
    family: 4,
  },
  (error) => {
    console.log(error)
    if (error && error.code === "ENOTFOUND") {
      console.log("OFFLINE")
    } else {
      console.log("ONLINE")
    }
  },
)
```

I wonder if this is something with lookup from node itself. To test this with your VS Code bundled Version you can check this table here: https://stackoverflow.com/a/65191145/4628787 (you can use pnpm or Volta to switch Node versions).

**Comment by MarcolinoPT** [comment]
Sorry for not replying sooner, I will take a look at this as soon as possible 😊

**Comment by MarcolinoPT** [comment]
Hey,

Finally got to test it with both VPNs and the result was the same
```bash
null
ONLINE
```

Afterward, I turned on `Auto Locale` then this message started popping up.
![image](https://user-images.githubusercontent.com/18648315/154106410-bb2440e0-ea13-472d-bcd4-15fff756058e.png)

I made sure no VPN was connected but the message still persisted, even after restarting VS Code.
I'm now using this version of VS Code:
![image](https://user-images.githubusercontent.com/18648315/154106845-af930f5a-98ed-4f62-9480-4f9a9429e542.png)

Is there anything else I can try helping you with?

**Comment by muuvmuuv** [comment]
Ok, so I have made some modifications to the codebase, and it appears that the API I have used to get lat and long is no longer available... for now just hard code your lat and long into the settings `sundial.latitude` and `sundial.longitude`. I will provide an update with some other changes once VS Code v1.65.0 is out (with Node16 support and other stuff) because I don't have the time ATM to create a new release nor access to my home computer (due to moving).

**Comment by muuvmuuv** [comment]
I release v3.0.0 which should fix this. Auto-publish is broken ATM so just Open VSX got the release, but I will fix that today

**Comment by MarcolinoPT** [comment]
So far so good, no more error messages 🙂 
Awesome work 💪🏻 thank you very much! 🙏🏻
