### ISSUE TITLE
Turning off auto-selection of a theme?

### ISSUE THREAD

**Issue by sehilyi** [muuvmuuv/vscode-sundial#57]
Is it possible to turn off the auto-selection between night and day themes?

I want to manually switch the theme so that whenever I open the vscode, just the previous theme is used.

**Comment by muuvmuuv** [comment]
Does it work for you, if you disable it through the Sundial command and manually switching with the commands?

**Comment by muuvmuuv** [comment]
Could be that VS Code "clears" defined settings in the extension context. I need to dig into this tomorrow/this week. But interesting. Maybe there is some kind of persistent storge I could use.

**Comment by muuvmuuv** [comment]
Should be fixed in 3.1.0. Can you confirm @sehilyi ?

**Comment by sehilyi** [comment]
Awesome, I can confirm that it is working
