### ISSUE TITLE
[FEATURE] Add a status bar icon

### ISSUE THREAD

**Issue by advait404** [muuvmuuv/vscode-sundial#59]
It would be nice to have a status bar icon to quickly toggle the theme, similar to the [Theme Switch](https://marketplace.visualstudio.com/items?itemName=Fooxly.themeswitch) extension.

**Comment by muuvmuuv** [comment]
Should be easy, I will have a look.

**Comment by muuvmuuv** [comment]
@advait404 latest release should include it, please test ^^ README is updated with notes.

**Comment by muuvmuuv** [comment]
Oh sh*** GH actions failed. Will fix this asap
