### ISSUE TITLE
[FEATURE] Fade into other theme on theme switch

### ISSUE THREAD

**Issue by georglauterbach** [muuvmuuv/vscode-sundial#60]
**Is your feature request related to a problem? Please describe.**

I'd like to see a fade, which would look quite cool, when switching to the other theme.

**Describe the solution you'd like**

A new option

```jsonc
"sundial.fadeDuration": 0 // default
```

The default is 0. When the user selects a value `>0`, a fade in milliseconds is applied.

**Describe alternatives you've considered**

`undefined`

**Additional context**

Would look cool :D

**Comment by sushart** [comment]
Oh yeah, that would be awesome.

**Comment by muuvmuuv** [comment]
Yes, that would look quite nice, but I do not think this would be possible, because I would need to inject some global CSS into VS Code to give any element a transition or something like that. There is also no API for things like this as I know.

**Comment by georglauterbach** [comment]
I already thought that this may be difficult. Thank you very much for letting me know, though! To keep track of my open issues, I will close this issue :)
